#!/usr/bin/env Rscript

#################################################
## Project: AHR IL4I1
## Origin: https://github.com/ahmedasadik/AHR_IL4I1_manuscript/AHR_signature/
## Date: Oct 2018
## Author: Ahmed Sadik (a.sadik@dkfz.de)
##
## Description
## This files describes how the associations between IL4I1 and different immune cells were made
################################################

## Load libraries
library(purrr)
library(Hmisc)
library(edgeR)
library(pheatmap)
library(psych)
library(ggpubr)
library(survival)
library(survminer)
library(RColorBrewer)
library(ggpubr)
library(MOFA)

## Source the functions and parameters files
source("./functions_and_parameters.R")

## Loading the immune infiltration scores generated by GSVA of the immunophenogram paper
# Infiltration scores
TCGA_IS2 <- readRDS("/media/ahmed/a4af7ffd-7367-425b-84ae-63ee9d3ddba8/Projects_analyses/AHR_IL4I1/AHR/Publication_results/Resources/RDS/TCGA_GSVA_voom_28_cell_types_IPS.rds")

## Loading the log2 CPM counts data, prior =1 of all TCGA tumors
TCGA_counts <- readRDS("/media/ahmed/51e78aee-a4ef-4ec6-83d8-39d15f6179e7/Processed/TCGA/RNAseqV2/TCGA_counts.rds")
names(TCGA_counts) <- tcga_names

######################################################################################
## Showing the difference in immune infiltration of median separated IL4I1 patients ##
######################################################################################
# Create lists of IL4I1 expression
IL4I1_tpm <- map(TCGA_counts, function(x)x[rownames(x)%in%c("IL4I1", "IDO1","TDO2"),]%>%t(.) %>%data.frame(.))

# Run the difference between the groups based on IL4I1 median separation
limma_res_IL4I1 <- map2(TCGA_IS2, IL4I1_tpm, function(a1,b1,l_b,u_b){
  b1$mz_goi <- (b1$IL4I1-median(b1$IL4I1))/(stats::mad(b1$IL4I1))
  # high low groups dataframe
  b1$group <- "avg"
  b1$group[which(b1$mz_goi < l_b)] <- "low"
  b1$group[which(b1$mz_goi >= u_b)] <- "high"
  if(l_b==0){
    b1$group
    b1$group <- factor(b1$group, levels = c("low","high"))
  } else {
    b1 <-b1[b1$group!="avg",]
    b1$group <- factor(b1$group, levels = c("low","high"))
  }
  a1 <- a1[,match(rownames(b1), colnames(a1))]
  design <- model.matrix(~b1$group)
  fit <- lmFit(a1, design = design)
  fit2 <- eBayes(fit)
  tt <- topTable(fit2, coef = 2, number = Inf, sort.by = "M")
  tt <- data.frame(cells=rownames(tt),tt, stringsAsFactors = F)
}, l_b=0,u_b=0)

# Create separate FC with cutoff of 0.3
limma_FC_df_IL4I1 <- map2(limma_res_IL4I1,names(limma_res_IL4I1), function(a,b){
  a$logFC[a$logFC<=0.3] <- NA
  df_fc <- (a$logFC) %>% t() %>% as.data.frame()
  rownames(df_fc) <- b
  colnames(df_fc) <- a$cells
  df_fc
}) %>% do.call(rbind,.) %>% .[,order(colSums(.), decreasing = T)]

# Creat separate adjusted p-value matrix 
limma_APV_df_IL4I1 <- map2(limma_res_IL4I1,names(limma_res_IL4I1), function(a,b){
  df_fc <- (a$adj.P.Val) %>% t() %>% as.data.frame()
  rownames(df_fc) <- b
  colnames(df_fc) <- a$cells
  df_fc
}) %>% do.call(rbind,.) %>% .[,match(colnames(limma_FC_df_IL4I1), colnames(.))]

# Print a heatmap that shows the cell types that are differentially regulated in high vs low IL4I1 groups
pdf("./Inf_cells_heatmap_logFC_0.3_apv_0.05_IL4I1_IFNG.pdf")
corrplot::corrplot(corr=as.matrix(limma_FC_df_IL4I1),p.mat = as.matrix(limma_APV_df_IL4I1),
                   sig.level = 0.05, method = "square",is.corr = F,title = "IL4I1 High vs Low",
                   insig = "blank",na.label = "square", na.label.col = "white",
                   col = colorRampPalette(colors = c("blue","red"))(7),
                   cl.length = 5,mar = c(0,0,2,0),
                   tl.cex = 0.7, cl.pos = "b",
                   tl.col = "black")
dev.off()

# Print a bargraph that shows the incidince of the different cell types across all tumors after the high-low comparison
incidince_plot <- map2(limma_FC_df_IL4I1, limma_APV_df_IL4I1, function(x,y){
  df <- data.frame(x,y)
  df$z <- ifelse(!is.na(df$x) & df$y<=0.05,1,0)
}) %>% do.call(cbind,.) %>% colSums() %>% data.frame(cells=names(.),vals=., stringsAsFactors = F) %>% .[order(.$vals),]
ip <- ggbarplot(incidince_plot, x="cells", y="vals", fill = "grey55", color = "grey55", ylab = "incidence")+coord_flip()

pdf("./Results/Figures/Inf_cells_incidince_logFC_0.3_apv_0.05_IL4I1.pdf")
ip
dev.off()


library(purrr)
library(Hmisc)
library(edgeR)
library(pheatmap)
library(psych)
library(ggpubr)
library(survival)
library(survminer)
library(RColorBrewer)
library(ggpubr)
library(MOFA)

set.seed(0861)
TCGA_names <- c("ACC", "BLCA", "BRCA", "CESC", "CHOL", "COAD", "DLBC",
                "ESCA", "GBM", "HNSC", "KICH", "KIRC", "KIRP", "LGG", "LIHC",
                "LUAD", "LUSC", "MESO", "OV", "PAAD", "PCPG", "PRAD", "READ",
                "SARC", "SKCM", "STAD", "TGCT", "THCA", "THYM", "UCEC", "UCS", "UVM")
## Run MOFA
# Load the immune infiltration data
TCGA_ImmScores <- readRDS("/media/ahmed/a4af7ffd-7367-425b-84ae-63ee9d3ddba8/Projects_analyses/AHR_IL4I1/AHR/Publication_results/Resources/RDS/TCGA_GSVA_voom_28_cell_types_IPS.rds")

# load the WGCNA modules
TCGA_modules <- readRDS("/media/ahmed/a4af7ffd-7367-425b-84ae-63ee9d3ddba8/Projects_analyses/AHR_IL4I1/AHR/Publication_results/Resources/RDS/TCGA_TOMS_bicor.rds")

library(MultiAssayExperiment)
library(MOFA)

TCGA_combined <- map(1:32, function(i){
  c_l <- list(wgcna=t(TCGA_modules[[i]]$MEs), immune=TCGA_ImmScores[[i]])
  colnames(c_l$wgcna) <- colnames(c_l$immune) <- substring(colnames(c_l$immune),1,12)
  c_l$immune <- c_l$immune[,which(duplicated(colnames(c_l$immune))==FALSE)]
  c_l$immune <- c_l$immune[,order(colnames(c_l$immune))]
  c_l$wgcna <- c_l$wgcna[,which(duplicated(colnames(c_l$wgcna))==FALSE)]
  c_l$wgcna <- c_l$wgcna[,order(colnames(c_l$wgcna))]
  c_l
})

names(TCGA_combined) <- TCGA_names

TCGA_MOFA <- map(TCGA_combined, function(x){
  MOFAobject <- createMOFAobject(x)
  MOFAobject
  
  DataOptions <- getDefaultDataOptions()
  DataOptions 
  ModelOptions <- getDefaultModelOptions(MOFAobject)
  ModelOptions$numFactors <- 25
  ModelOptions
  
  TrainOptions <- getDefaultTrainOptions()
  # Automatically drop factors that explain less than 2% of variance in all omics
  TrainOptions$DropFactorThreshold <- 0.02
  TrainOptions$seed <- 0861
  TrainOptions
  MOFAobject <- prepareMOFA(
    MOFAobject, 
    DataOptions = DataOptions,
    ModelOptions = ModelOptions,
    TrainOptions = TrainOptions
  )
  
  MOFAobject <- runMOFA(MOFAobject)
})

saveRDS(TCGA_MOFA,"/home/ahmed/Documents/Projects/General/TCGA_MOFA_wgcna_immune_mutations.RDS")

## Prepare for the MOFA circular plots
library(ComplexHeatmap)
library(circlize)

TCGA_modules_genes <- readRDS("/media/ahmed/a4af7ffd-7367-425b-84ae-63ee9d3ddba8/Projects_analyses/AHR_IL4I1/AHR/Publication_results/Resources/RDS/TCGA_modules_genes.rds")
names(TCGA_modules_genes) <- gsub("TCGA_","",names(TCGA_modules_genes))
IL4I1_modules <- map(TCGA_modules_genes,function(x){x$module[x$genes=="IL4I1"]})

## Create a dataframe with the first 5 factors from the MOFA run for the immune and wgcna views
lf_mat_immune <- map2(TCGA_MOFA,names(TCGA_MOFA),function(mof_obj,tumor){
  var_r2 <- calculateVarianceExplained(mof_obj)$R2PerFactor
  df <- data.frame(tumor=tumor, LF=rownames(var_r2),var_r2, stringsAsFactors = F) %>% .[1:5,]
}) %>% do.call(rbind,.)

## Color function for the heatmap of the factors
col_fun = colorRamp2(c(0, 0.8), c("grey90", "blue"))

## matrix for the run
mat2=lf_mat_immune
mat3 <- mat2[,-c(1:2)] %>% t()
factors2 <- factor(mat2$tumor)

## The tumors are reordered based on the coordinates of their location on the plot
to_subset <- as.character(levels(factors2))

## The latent factors that we are showing for the different tumors ordered as to_subset
LFs_to_show <- as.numeric(c(rep(1,11),2,4,rep(1,8),2,1,2,rep(1,5),4,1,1))
names(LFs_to_show) <- to_subset

## Generating matrices of the wgcna view for the top 10 features with weights in this view and assigning the module with IL4I1 a color
wgcna_weights <- map2(to_subset,LFs_to_show,function(mof_obj,factor,view){
  W <- getWeights(TCGA_MOFA[[mof_obj]], views = view, factors = factor, as.data.frame = TRUE)
  W$value <- W$value/max(abs(W$value))
  W$group <- "0"
  W$group[abs(W$value) >= sort(abs(W$value), decreasing = TRUE)[10]] <- "1"
  W <- W[W$group=="1",]
  df <- data.frame(tumor=mof_obj,W)
  df$feature <- gsub("ME","",df$feature)
  df$color <- "grey"
  df$color[df$feature==IL4I1_modules[[mof_obj]]] <- "red"
  df <- df[order(df$value,decreasing = T),]
  df$xval <- seq(0.35,4.75,0.45)
  df
},view="wgcna") %>% do.call(rbind,.)

## Generating matrices of the immune view for the top 10 features with weights in this view
immune_colors <- c(brewer.pal(6,"Set2"),brewer.pal(12,"Paired"),brewer.pal(8,"Dark2"))
immune_weights <- map2(to_subset,LFs_to_show,function(mof_obj,factor,view){
  W <- getWeights(TCGA_MOFA[[mof_obj]], views = view, factors = factor, as.data.frame = TRUE)
  W$value <- W$value/max(abs(W$value))
  W$group <- "0"
  W$group[abs(W$value) >= sort(abs(W$value), decreasing = TRUE)[10]] <- "1"
  W$feature <- gsub(" ","",W$feature)
  W$color <- "grey"
  W$color[W$feature=="Activated_CD8_T_cell"] <- brewer.pal(6,"Set2")[1]
  W$color[W$feature=="Effector_memeory_CD8_T_cell"] <- brewer.pal(6,"Set2")[2]
  W$color[W$feature=="Activated_CD4_T_cell"] <- brewer.pal(6,"Set2")[3]
  W$color[W$feature=="Effector_memeory_CD4_T_cell"] <- brewer.pal(6,"Set2")[4]
  W$color[W$feature=="MDSC"] <- brewer.pal(6,"Set2")[5]
  W$color[W$feature=="Regulatory_T_cell"] <- brewer.pal(6,"Set2")[6]
  W <- W[W$group=="1",]
  df <- data.frame(tumor=mof_obj,W)
  df <- df[order(df$value,decreasing = T),]
  df$xval <- seq(0.35,4.75,0.45)
  df
},view="immune") %>% do.call(rbind,.)

## The matrices for the heatmaps
mat_list2.0 <- map(to_subset, function(x){mat3[,factors2==x]})
names(mat_list2.0) <- to_subset

## setting the limits for the first track giving all tumors the same sector size
x_limits <- cbind(rep(0,length(to_subset)), table(factors2))

## Generate the circos plot for the MOFA LFs with modules containing IL4I1
circos_figure <- function(){
  ## plot outline
  circos.par(cell.padding = c(0, 0, 0, 0),gap.degree = 1)
  ## Begin plotting by initializing the plot area
  circos.initialize(to_subset, xlim = x_limits)
  ## Plot the heat map of the first 5 latent factors of the different tumors
  circos.track(ylim = c(0, dim(mat3)[1]), track.height=0.05,bg.border = NA, panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    m2 = mat_list2.0[[sector.index]]
    col_mat = col_fun(m2)
    nr = nrow(m2)
    nc = ncol(m2)
    for(i in 1:nr) {
      circos.rect(1:nc - 1, rep(nr - i, nc), 1:nc, rep(nr - i + 1, nc), border = col_mat[i, ], col = col_mat[i, ])
    }
  })
  ## add tumor names to this track
  map(to_subset,function(z,b){
    circos.text(2.5, 3, labels=z, sector.index = z, cex=0.6,
                facing = "inside", niceFacing = TRUE, col = "black")
  })
  
  ## Add lines from the LFs used to the lolliplots
  circos.track(ylim=c(0,1), track.height=0.03, bg.border = NA, panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    for(i in sector.index){
      if(LFs_to_show[[i]]==1){
        circos.segments(sector.index = i, x0=0, x1=0, y0=0, y1=1,col = "black")
        circos.segments(sector.index = i, x0=1, x1=1, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=0, x1=1, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=1, x1=5, y0=0.8, y1=0,col = "black")
        circos.segments(sector.index = i, x0=0, x1=0, y0=0, y1=0,col = "black")
      } else if(LFs_to_show[[i]]==2){
        circos.segments(sector.index = i, x0=1, x1=1, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=2, x1=2, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=1, x1=2, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=2, x1=5, y0=0.8, y1=0,col = "black")
        circos.segments(sector.index = i, x0=1, x1=0, y0=0.8, y1=0,col = "black")
      } else if(LFs_to_show[[i]]==3){
        circos.segments(sector.index = i, x0=2, x1=2, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=3, x1=3, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=2, x1=3, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=3, x1=5, y0=0.8, y1=0,col = "black")
        circos.segments(sector.index = i, x0=2, x1=0, y0=0.8, y1=0,col = "black")
      } else if(LFs_to_show[[i]]==4){
        circos.segments(sector.index = i, x0=3, x1=3, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=4, x1=4, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=3, x1=4, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=4, x1=5, y0=0.8, y1=0,col = "black")
        circos.segments(sector.index = i, x0=3, x1=0, y0=0.8, y1=0,col = "black")
      } else if(LFs_to_show[[i]]==5){
        circos.segments(sector.index = i, x0=4, x1=4, y0=0.8, y1=1,col = "black")
        circos.segments(sector.index = i, x0=5, x1=5, y0=0, y1=1,col = "black")
        circos.segments(sector.index = i, x0=4, x1=5, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=5, x1=5, y0=1, y1=1,col = "black")
        circos.segments(sector.index = i, x0=4, x1=0, y0=0.8, y1=0,col = "black")
      }
    }
    
  })
  
  ## Plot the second track with the wgcna lolliplots of the 10 most weighted factors
  circos.track(ylim=c(-1.2,1.2), track.height=0.15, bg.border = "black", panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    m4 = wgcna_weights[wgcna_weights$tumor==sector.index,]
    circos.points(x=m4$xval,y=m4$value, col = m4$color, pch=19)
    circos.lines(x=c(0,5),y=c(0,0),col = "lightblue")
    for(i in seq_along(m4$xval)){
      circos.lines(x=c(m4$xval[i],m4$xval[i]),y=c(0,m4$value[i]),col = m4$color[i])  
    }
  })
  circos.track(ylim=c(-1.2,1.2), track.height=0.15, bg.border = "black", panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    m4 = immune_weights[immune_weights$tumor==sector.index,]
    m4 = m4[m4$feature%in%c("Regulatory_T_cell","MDSC"),]
    circos.points(x=m4$xval,y=m4$value, col = m4$color, pch=19)
    circos.lines(x=c(0,5),y=c(0,0),col = "lightblue")
    for(i in seq_along(m4$xval)){
      circos.lines(x=c(m4$xval[i],m4$xval[i]),y=c(0,m4$value[i]),col = m4$color[i])  
    }
  })
  circos.track(ylim=c(-1.2,1.2), track.height=0.15, bg.border = "black", panel.fun = function(x, y) {
    sector.index = CELL_META$sector.index
    m4 = immune_weights[immune_weights$tumor==sector.index,]
    m4 = m4[m4$feature%in%c("Activated_CD8_T_cell","Effector_memeory_CD8_T_cell","Activated_CD4_T_cell","Effector_memeory_CD4_T_cell"),]
    circos.points(x=m4$xval,y=m4$value, col = m4$color, pch=19)
    circos.lines(x=c(0,5),y=c(0,0),col = "lightblue")
    for(i in seq_along(m4$xval)){
      circos.lines(x=c(m4$xval[i],m4$xval[i]),y=c(0,m4$value[i]),col = m4$color[i])  
    }
  })
  circos.clear()
}

# discrete
lgd_IL4I1 = Legend(at = c("IL4I1 module"), type = c("points","lines"), background = "white",
                   legend_gp = gpar(col = "red"), title_position = "topleft", 
                   title = "WGCNA_view")
# discrete
lgd_Imm = Legend(at = c("Act CD8", "Eff-mem CD8","Act CD4", "Eff-mem CD4","MDSC","Tregs"),
                 type = c("points","lines"), background = "white",
                 legend_gp = gpar(col = brewer.pal(6,"Set2"),lineend="round"), title_position = "topleft", 
                 title = "Immune_view")
# continuous
lgd_LFs = Legend(at = c(0, 0.2, 0.4, 0.6, 0.8), col_fun = col_fun, 
                 title_position = "topleft", title = "LFs_R2")

lgd_list_vertical = packLegend(lgd_IL4I1, lgd_Imm)

pdf("~/Desktop/MOFA_circos.pdf",width = 8,height = 8)
circos_figure()
draw(lgd_list_vertical, x = unit(4, "mm"), y = unit(4, "mm"), just = c(-2.8, -2.05))
draw(lgd_LFs, x = unit(4, "mm"), y = unit(4, "mm"), just = c(-8.4, -3.55))
dev.off()
